### PR TITLE
changed some comments and wrote first test.

### PR DESCRIPTION
**Pull request by JohnAD**
Thank you for creating a pull request to contribute to FreeCAD! Place an "X" in between the brackets below to "check off" to confirm that you have satisfied the requirement, or ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10) if there is something you don't understand.

- [ ]  Your Pull Request meets the requirements outlined in section 5 of [CONTRIBUTING.md](https://github.com/FreeCAD/FreeCAD/blob/master/CONTRIBUTING.md) for a Valid PR

Please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [1.0 Changelog Forum Thread](https://forum.freecad.org/viewtopic.php?f=10&t=69438).

---

### CODE REVIEW

**Comment by JohnAD** [comment]
I also began testing, but commented out, the `setElementName` test.

I want to work through it more carefully later in my head, but I suspect that function should be a member of `ElementMapPtr` rather than `ElementMap`. And there should be no parameter for an `ElementMapPtr` reference. Of course, changing that might also change `addName` and a few other things.

**Comment by JohnAD** [comment]
I leave this for reference; but don't accept this PR. It's got weird merge resolution problems :grin: 

John

**Comment by JohnAD** [comment]
Actually, I got it working, I think, without the `ElementMapPtr`; keeping it clean. I also created a private `init` function so the code can be directly called outside the constructor.

I put it on another branch: https://github.com/MakerReduxCorp/FreeCAD-Pesc0/tree/non-pointer

There are two more tests on that branch: https://github.com/MakerReduxCorp/FreeCAD-Pesc0/blob/non-pointer/tests/src/App/ElementMap.cpp#L32

I seem to have [redacted] the heck out of my git history on that branch. Feel free to just cut & paste code changes into the branch on your repo. I'm not concerned with getting commit history credit :grin: .

**Comment by Pesc0** [comment]
Sorry I've totally missed this. Could you check that I've integrated your changes properly? Currently it builds fine but tests fail:
```
[ RUN      ] ElementMapTest.setElementNameDefaults
FreeCAD/src/Base/Type.cpp:157: static void Base::Type::init(): Assertion 'Type::typedata.size() == 0' failed.
Aborted (core dumped)
```

**Comment by Pesc0** [comment]
I've added a couple of comments to your latest commit: https://github.com/Pesc0/FreeCAD/commit/3771d82f8542ff2d5f3d0d0700b14d4bbbd8bc37

To avoid additional merge conflicts:
- I will close this PR
- please rebase your branches on latest Pesc0/elementmap and open a new PR

**Pull request closed without merging**
